### ISSUE TITLE
plan only for linux based machines

### ISSUE THREAD

**Issue by nicholasljk** [learn-chef/hab-two-tier#10]
The plan only works for linux based machines. Any guidance on how to convert it to powershell?

**Comment by nanowinner** [comment]
Seconded.

**Comment by jbrigleb** [comment]
Thirded

**Comment by coryreid** [comment]
I was initially fighting with this as well, but if you look at the tutorial, the goal is to run hab studio with the `-D` flag so it runs in Docker on a Linux host, which will allow you to build the plan.sh

I agree that I'd like to see more flexibility for a plan.ps1 version, but I think there's some nice reference material [here](https://www.habitat.sh/demo/windows/steps/1/) for Windows specific usage.
